ALTER TABLE indirizzo_postale
ALTER COLUMN indirizzo TYPE VARCHAR(70),
ALTER COLUMN citta TYPE VARCHAR(35),
ALTER COLUMN cap TYPE VARCHAR(16),
ALTER COLUMN divisione TYPE VARCHAR(70),
ALTER COLUMN sotto_divisione TYPE VARCHAR(35),
ALTER COLUMN numero_civico TYPE VARCHAR(16),
ALTER COLUMN piano TYPE VARCHAR(70),
ALTER COLUMN cassetta_postale TYPE VARCHAR(16),
ALTER COLUMN stanza TYPE VARCHAR(70),
ALTER COLUMN localita TYPE VARCHAR(35),
ALTER COLUMN distretto TYPE VARCHAR(35),
ALTER COLUMN provincia TYPE VARCHAR(35);
