package com.flowpay.ccp.credit.transfer.cross.border.persistence.credit.transfer.status.inserted;

public enum InsertedSubStatus {
    CONTROLLO_SISTEMA_DI_REGOLAMENTO_IN_ATTESA,
    CONTROLLO_SISTEMA_DI_REGOLAMENTO_FALLITO,
    CONTROLLO_SISTEMA_DI_REGOLAMENTO_PASSATO,

    CONTROLLO_INSERIMENTO_IN_ATTESA,
    CONTROLLO_INSERIMENTO_DA_CONFERMARE,
    CONTROLLO_INSERIMENTO_FALLITO,
    CONTROLLO_INSERIMENTO_PASSATO,

    CONFERMA_IN_ATTESA,
    CONFERMA_DA_CONFERMARE,
    CONFERMA_FALLITO,
    CONFERMA_PASSATO
}
